### PR TITLE
Made compatible with Python 3

### LINKED ISSUE #3: Setup CI
We should setup either a travis or solano CI to make sure the builds are passing always.

### PR DESCRIPTION
**Pull request by migurski**
Fixes for Python 3 compatibility in a few areas:

* `str` vs. `bytes` issues.
* `pickle` vs. `cPickle` imports.
* `xrange` and `basestring` usage.
* Iterator protocol usage.
* Pickle vs. JSON compatibility.

Also added Travis CI configuration to close #3, and [verified that all tests pass](https://travis-ci.org/migurski/pq/builds/62006276). Would love to see this released to PyPI soon, using it in a project with Python 3!

### CODE REVIEW

**Comment by malthe** [comment]
Packaged and uploaded as ``pq--1.3``.

**Comment by migurski** [comment]
Thank you!

**Comment by NelsonMinar** [comment]
Terrific, thanks!

**Comment by stas** [comment]
:+1:

**Pull request merged**
