### PR TITLE
Add support for using a custom schema

### PR DESCRIPTION
**Pull request by malthe**
## What is the new behavior?

This fixes issue #35.

## Checklist

Please make sure the following requirements are complete:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes /
  features)
- [ ] All automated checks pass (CI/CD)

### CODE REVIEW

**Comment by malthe** [comment]
@stas what do you think about this?

**Comment by stas** [comment]
@malthe it's not clear from the changeset if the interface of the API calls changed, it would be nice to have the default `schema` work without changing anything by the end-users. Otherwise, this looks great :rocket: :upside_down_face:

**Comment by malthe** [comment]
@stas that's been fixed now – code is simplified as well.

**Review by stas — APPROVED** [review]
:rocket: :heart: :raised_hands:

**Pull request merged**
